"""Asserts every uipath.json under examples/ matches the schema that
`uipath init` actually writes.

Earlier drafts hand-authored uipath.json with AURORA-specific fields
(name, description, version, framework, model.tier, credentials,
tracing) — none of which the real schema accepts. Per resolution D1
in docs/grill-2026-05-09.md, manifests are now generated by `uipath init`
(captured shape frozen in tests/schemas/uipath_json.schema.json) and
AURORA's extras moved elsewhere: model_binding_tier into the
process-level bindings.json, credentials into per-agent
bindings.json::resources, tracing into main.py runtime.

Acceptance test for T-A3.
"""
from __future__ import annotations

import json
from pathlib import Path

import jsonschema  # type: ignore[import-untyped]
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "tests" / "schemas" / "uipath_json.schema.json"
EXAMPLES_DIR = REPO_ROOT / "examples"


def _agent_uipath_jsons() -> list[Path]:
    """Per-agent uipath.json files (under examples/.../agents/<name>/uipath.json)."""
    return sorted(EXAMPLES_DIR.rglob("agents/*/uipath.json"))


def _coded_workflow_uipath_jsons() -> list[Path]:
    """Per-coded-workflow uipath.json files (under examples/.../coded/<name>/uipath.json)."""
    return sorted(EXAMPLES_DIR.rglob("coded/*/uipath.json"))


def _all_uipath_jsons() -> list[Path]:
    return _agent_uipath_jsons() + _coded_workflow_uipath_jsons()


def _schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def test_schema_file_exists() -> None:
    assert SCHEMA_PATH.exists(), f"schema freeze missing: {SCHEMA_PATH}"


def test_at_least_one_uipath_json_present() -> None:
    """Sanity check — there should be at least one Coded Agent / Coded Workflow."""
    assert _all_uipath_jsons(), (
        "expected at least one uipath.json under examples/.../{agents,coded}/<name>/"
    )


@pytest.mark.parametrize("path", _all_uipath_jsons(), ids=lambda p: str(p.relative_to(REPO_ROOT)))
def test_uipath_json_validates_against_frozen_schema(path: Path) -> None:
    schema = _schema()
    payload = json.loads(path.read_text(encoding="utf-8"))
    jsonschema.validate(instance=payload, schema=schema)


@pytest.mark.parametrize("path", _all_uipath_jsons(), ids=lambda p: str(p.relative_to(REPO_ROOT)))
def test_uipath_json_has_no_aurora_legacy_fields(path: Path) -> None:
    """The pre-T-A3 hand-authored shape included these fields. They must not
    survive in any uipath.json — they belong in bindings.json or pyproject.toml."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    forbidden = ["name", "description", "version", "framework", "model", "credentials", "tracing"]
    leaked = [k for k in forbidden if k in payload]
    assert not leaked, (
        f"{path.relative_to(REPO_ROOT)} still has legacy AURORA fields: {leaked}. "
        f"Move name/description/version to pyproject.toml; framework is implicit; "
        f"model.tier → process-level bindings.json::tasks.<id>.model_binding_tier; "
        f"credentials → per-agent bindings.json::resources; tracing → runtime."
    )


def test_at_least_one_function_or_agent_declared() -> None:
    """Every uipath.json must declare at least one function or agent entry point —
    `uipath pack` warns and bails otherwise."""
    for path in _all_uipath_jsons():
        payload = json.loads(path.read_text(encoding="utf-8"))
        functions = payload.get("functions", {})
        agents = payload.get("agents", {})
        assert functions or agents, (
            f"{path.relative_to(REPO_ROOT)} has no functions or agents entries"
        )


def test_entry_points_json_mirrors_uipath_json_functions() -> None:
    """For each agent/coded-workflow with a uipath.json, an entry-points.json
    must exist alongside it and list every declared function as an entry point."""
    for path in _all_uipath_jsons():
        ep_path = path.parent / "entry-points.json"
        assert ep_path.exists(), f"missing {ep_path.relative_to(REPO_ROOT)}"
        ep_doc = json.loads(ep_path.read_text(encoding="utf-8"))
        assert ep_doc.get("$schema") == "https://cloud.uipath.com/draft/2024-12/entry-point"
        ep_ids = {ep["uniqueId"] for ep in ep_doc.get("entryPoints", [])}
        functions = json.loads(path.read_text(encoding="utf-8")).get("functions", {})
        for fn in functions:
            assert fn in ep_ids, (
                f"function '{fn}' in {path.relative_to(REPO_ROOT)} has no "
                f"matching entry in entry-points.json"
            )
